posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
        path('', views.index, name='index'),
        path('like/<int:id>', views.oneup, name='oneup'),
        path('post/', views.makechirp, name='makechirp'),
        path('user/<str:username>', views.user_home, name='users')
        ]

user_app/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('register/', views.register, name="register"),
    path('login_page/', views.login_page, name="login_page"),
    path('login_form/', views.login_form, name="login_form"),
    path('', views.home, name="home"),
    path('logout/', views.logout_user, name="logout")
    ]

user_auth/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('', include('user_app.urls')),
    path('admin/', admin.site.urls),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Chirps(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=128)
    date = models.DateTimeField(null=True)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.message

user_app/models.py
from django.db import models

# Create your models here.

posts/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from .models import Chirps
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def index(request):

    posts = Chirps.objects.all()

    context = {

            'posts': posts

            }

    return render(request, 'posts/index.html', context)

@login_required
def oneup(request, id):

    obj = get_object_or_404(Chirps, pk=id)
    obj.likes = obj.likes + 1
    obj.save()

    return HttpResponseRedirect(reverse('posts:index'))

@login_required
def makechirp(request):
    message = request.POST['message']
    user = request.user
     
    chirp = Chirps(user=user,  date=timezone.now(), message=message)
    chirp.save()
    return HttpResponseRedirect(reverse('posts:index'))

def user_home(request, username):
    user = get_object_or_404(User, username=username)
    user_posts = Chirps.objects.filter(user=user)
    return render(request,'posts/users.html', {'posts': user_posts})
		

user_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect

# Create your views here.
def signup(request):
    return render(request, 'user_app/signup.html')

def register(request):
    username = request.POST['username']
    password = request.POST['password']
    email = request.POST['email']

    user = User.objects.create_user(username, email, password)

    print(user)

    return HttpResponseRedirect(reverse('user_app:login_page'))

def login_page(request):
    return render(request, 'user_app/login.html')

def login_form(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        return HttpResponseRedirect(reverse('user_app:home'))
    else:
        # Return an 'invalid login' error message.
        return HttpResponseRedirect(reverse('user_app:login_page'))

def home(request):
    return render(request, 'user_app/home.html')

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('posts:index'))

posts/templates/posts/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
	   <meta charset="utf-8">
           <title></title>
	</head>
	<body>
		<header> <a href="/">Tweeter<header>
	<nav> 

		<a href="signup/">signup</a>
		<a href="login_page/">login</a>
		<a href="logout/">logout</a>
	</nav>

	<form method="post">
                {% csrf_token %}
				
		<input type="text" name="message"/> message
		<button type="submit" formaction="{% url 'posts:makechirp' %}">Post</button>
         
	</form>

	<form method="post">
                {% csrf_token %}
                {% for post in posts %}
                        <li>
				{{ post.user }} {{ post.message }} {{ post.date }} {{ post.likes }}
				<button type="submit" formaction="{% url 'posts:oneup' post.id %}">Like</button>
                        </li>
                    
                {% endfor %}
        </form>
        </ul>	
	</body>

</html>

posts/templates/posts/users.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
	   <meta charset="utf-8">
           <title></title>
	</head>
	<body>
		<header> <a href="/">Tweeter<header>
	<nav> 

		<a href="signup/">signup</a>
		<a href="login_page/">login</a>

	</nav>

         
                {% for post in posts %}
                        <li>
				{{ post.user }} {{ post.message }} {{ post.date }} {{ post.likes }}
                        </li>
                    
                {% endfor %}
        </form>
        </ul>	
	</body>

</html>

user_app/templates/user_app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome!</h1>
</body>
</html>

user_app/templates/user_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Login</h1>
    <form action="{% url 'user_app:login_form' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" required placeholder="username" />
        <input type="password" name="password" required placeholder="password" />
        <button type="submit">Login</button>
    </form>
</body>
</html>

user_app/templates/user_app/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Signup</h1>
    <form action="{% url 'user_app:register' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" required placeholder="username" />
        <input type="password" name="password" required placeholder="password" />
        <input type="email" name="email" required placeholder="email" />
        <button type="submit">Sign up</button>
    </form>
</body>
</html>